import React from 'react';
import { FiBookOpen, FiCheckCircle, FiClock, FiStar } from 'react-icons/fi';


export interface Stat {
  icon: React.ReactNode;
  value: string;
  label: string;
  color: string;
  bgColor: string;
}

export interface Filter {
  label: string;
  count: number;
}

export interface SubTopic {
  title: string;
  explanation: string;
  examples?: string[];
}

export interface Lesson {
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  title: string;
  description: string;
  time: number;
  category: string;
  subTopics: SubTopic[];
}




export const learnPageStats: Stat[] = [
  { icon: <FiBookOpen className="text-blue-500" />, value: '37', label: 'Total Lessons', color: 'text-blue-500', bgColor: 'bg-blue-100' },
  { icon: <FiCheckCircle className="text-green-500" />, value: '0', label: 'Completed', color: 'text-green-500', bgColor: 'bg-green-100' },
  { icon: <FiClock className="text-yellow-500" />, value: '0', label: 'In Progress', color: 'text-yellow-500', bgColor: 'bg-yellow-100' },
  { icon: <FiStar className="text-purple-500" />, value: 'N/A', label: 'Avg. Score', color: 'text-purple-500', bgColor: 'bg-purple-100' },
];

export const learnPageFilters: Filter[] = [
  { label: 'All Lessons', count: 37 },
  { label: 'Grammar', count: 7 },
  { label: 'Tenses', count: 4 },
  { label: 'Vocabulary', count: 6 },
  { label: 'Politeness and Professional', count: 6 },
  { label: 'Advanced Grammar', count: 5 },
  { label: 'Usage In Context', count: 6 },
  { label: 'Writing Skills', count: 3 },
];

export const learnPageLessons: Lesson[] = [
  
  { level: 'Beginner', title: 'Everyday Words', category: 'Vocabulary', description: 'Build your foundation with essential words for daily conversations.', time: 15, subTopics: [ { title: 'Greetings and Introductions', explanation: 'Learn how to greet people and introduce yourself confidently in various social and professional settings.', examples: ['Formal: "Hello, my name is John. It\'s a pleasure to meet you."', 'Informal: "Hi, I\'m Sarah. Nice to meet you!"'] }, { title: 'Food and Drink', explanation: 'Use this vocabulary when you go to a restaurant, cafe, or talk about meals with friends and colleagues.', examples: ['Ordering: "I would like to order the chicken sandwich, please."', 'Question: "Could I have a glass of water?"'] } ] },
  { level: 'Advanced', title: 'Professional Vocabulary', category: 'Vocabulary', description: 'Learn the specific terms and jargon used in a corporate environment.', time: 25, subTopics: [ { title: 'Business Meetings', explanation: 'These are key phrases and terms you will hear and use in a professional meeting to sound confident and competent.', examples: ['Agenda: "Let\'s stick to the agenda to stay on track."', 'Action Items: "My main action item is to email the client."'] }, { title: 'Negotiation Terms', explanation: 'Understanding these terms is crucial for any business negotiation to ensure you can contribute effectively.', examples: ['Counter-offer: "They rejected our price, but they made a counter-offer."', 'Leverage: "Our strong market position gives us more leverage in this deal."'] } ] },
  { level: 'Intermediate', title: 'Idioms and Phrases', category: 'Vocabulary', description: 'Sound more like a native speaker by using common idioms correctly.', time: 20, subTopics: [ { title: 'Money Idioms', explanation: 'These phrases are commonly used in informal conversations to talk about money and expenses.', examples: ['"The new car cost an arm and a leg." (It was very expensive)', '"I can\'t go to the concert; I need to tighten my belt this month." (I need to save money)'] }, { title: 'Time Idioms', explanation: 'Expressions related to time help make your language more colorful and descriptive.', examples: ['"He arrived in the nick of time, just before the train left."', '"An opportunity like this only comes once in a blue moon."'] } ] },
  { level: 'Intermediate', title: 'Commonly Confused Words', category: 'Vocabulary', description: 'Avoid common mistakes by learning the difference between similar words.', time: 18, subTopics: [ { title: 'Affect vs. Effect', explanation: 'A good rule to remember is that "affect" is usually a verb (to influence something), and "effect" is usually a noun (the result of something).', examples: ['Correct: "The rain will affect our plans."', 'Correct: "The effect of the rain was a flood."'] }, { title: 'Then vs. Than', explanation: '"Then" is used for time or sequence. "Than" is used for comparisons.', examples: ['Correct: "First we will eat, and then we will go to the movies."', 'Correct: "She is taller than her brother."'] } ] },
  { level: 'Intermediate', title: 'Synonyms and Antonyms', category: 'Vocabulary', description: 'Expand your word choice to make your speaking and writing more dynamic.', time: 20, subTopics: [ { title: 'Understanding Nuance', explanation: 'Discover how synonyms can have slightly different meanings and connotations.', examples: ['"Happy" and "Joyful" are synonyms, but "joyful" implies a deeper, more expressive happiness.'] }, { title: 'Using Stronger Verbs', explanation: 'Replace common verbs with more powerful and descriptive synonyms.', examples: ['Instead of "walk," you could use "stroll," "stride," or "march."'] } ] },
  { level: 'Intermediate', title: 'Phrasal Verbs', category: 'Vocabulary', description: 'Master common phrasal verbs that are essential for fluent conversation.', time: 22, subTopics: [ { title: 'Phrasal Verbs with "Get"', explanation: 'Learn expressions like "get up," "get along," and "get over."', examples: ['"What time do you usually get up in the morning?"', '"I get along well with my coworkers."'] }, { title: 'Phrasal Verbs with "Take"', explanation: 'Understand and use phrases such as "take off," "take on," and "take up."', examples: ['"The plane will take off in an hour."', '"She decided to take on the extra responsibilities."'] } ] },

  
  { level: 'Beginner', title: 'Present, Past, and Future Tenses', category: 'Tenses', description: 'Learn the fundamental verb tenses to talk about different points in time.', time: 18, subTopics: [ { title: 'Simple Present', explanation: 'Used for habits, unchanging situations, general truths, and fixed arrangements.', examples: ['Habit: "She drinks coffee every morning."', 'General Truth: "The sun rises in the east."'] }, { title: 'Simple Past', explanation: 'Used to talk about a completed action in a time before now.', examples: ['"I went to the library yesterday."', '"We saw a good film last week."'] }, { title: 'Simple Future', explanation: 'Used for actions that will happen in the future, often with "will" or "be going to."', examples: ['"I will call you tomorrow."', '"She is going to start her new job next month."'] } ] },
  { level: 'Intermediate', title: 'Continuous and Perfect Tenses', category: 'Tenses', description: 'Understand more complex tenses to describe ongoing or completed actions.', time: 25, subTopics: [ { title: 'Present Continuous', explanation: 'For actions happening right now or around the current time.', examples: ['"I am currently working on a new project."', '"She is studying to become a doctor."'] }, { title: 'Past Perfect', explanation: 'For an action that happened before another past action.', examples: ['"The train had already left when I arrived at the station."'] }, { title: 'Present Perfect vs. Past Simple', explanation: 'Learn the key differences between these two commonly confused tenses.', examples: ['Past Simple: "I visited Paris in 2019." (Specific past time)', 'Present Perfect: "I have visited Paris three times." (Unspecified time, experience)'] } ] },
  { level: 'Advanced', title: 'Active and Passive Voice', category: 'Tenses', description: 'Learn how to change the focus of a sentence by using the active or passive voice.', time: 20, subTopics: [ { title: 'Forming the Passive Voice', explanation: 'Understand the structure (to be + past participle) to form passive sentences.', examples: ['Active: "The team completed the project."', 'Passive: "The project was completed by the team."'] }, { title: 'When to Use the Passive', explanation: 'Learn why the passive voice is common in formal and scientific writing, or when the actor is unknown.', examples: ['Formal: "The report was published last month."', 'Unknown Actor: "My car was stolen."'] } ] },
  { level: 'Beginner', title: 'Question Formation and Negatives', category: 'Tenses', description: 'Learn how to properly form questions and negative sentences in English.', time: 15, subTopics: [ { title: 'Yes/No Questions', explanation: 'Forming questions with auxiliary verbs like "do," "be," and "have."', examples: ['"Do you like coffee?"', '"Is she from Ethiopia?"'] }, { title: '"Wh-" Questions', explanation: 'Using "who," "what," "where," "when," and "why" to ask for information.', examples: ['"Where do you live?"', '"What time is the meeting?"'] }, { title: 'Making Negative Sentences', explanation: 'Using "not" to form negative statements in various tenses.', examples: ['"I do not like tea."', '"She is not coming to the party."'] } ] },

  
  { level: 'Beginner', title: 'Articles: A, An, The', category: 'Grammar', description: 'Learn the rules for using definite and indefinite articles correctly.', time: 15, subTopics: [ { title: 'Indefinite Articles (a/an)', explanation: 'When to use "a" and "an" for general, non-specific nouns.', examples: ['"I need a new phone."', '"She is an engineer."'] }, { title: 'Definite Article (the)', explanation: 'When to use "the" for specific, previously mentioned, or unique nouns.', examples: ['"The phone I bought is black."', '"The sun is very bright today."'] }, { title: 'Zero Article', explanation: 'Learn about situations where no article is needed, such as with general plural nouns.', examples: ['"I like dogs."', '"She studies biology."'] } ] },
  { level: 'Beginner', title: 'Subject-Verb Agreement', category: 'Grammar', description: 'Ensure your subjects and verbs match to create grammatically correct sentences.', time: 18, subTopics: [ { title: 'Singular and Plural Nouns', explanation: 'Matching singular subjects with singular verbs and plural subjects with plural verbs.', examples: ['Singular: "The dog barks."', 'Plural: "The dogs bark."'] }, { title: 'Compound Subjects', explanation: 'Learn the rules for subjects connected by "and" or "or."', examples: ['"My brother and sister live in Addis Ababa."', '"Either the manager or the employees have the key."'] } ] },
  { level: 'Intermediate', title: 'Prepositions of Time and Place', category: 'Grammar', description: 'Master the use of "in," "on," and "at" for both time and location.', time: 20, subTopics: [ { title: 'Prepositions of Time', explanation: 'Using "in" for months/years, "on" for days/dates, and "at" for specific times.', examples: ['"The meeting is on Monday at 10 AM."', '"Her birthday is in April."'] }, { title: 'Prepositions of Place', explanation: 'Using "in" for enclosed spaces, "on" for surfaces, and "at" for specific points.', examples: ['"The keys are on the table."', '"He is at the airport."'] } ] },
  { level: 'Intermediate', title: 'Conjunctions', category: 'Grammar', description: 'Connect ideas, clauses, and sentences smoothly using conjunctions.', time: 16, subTopics: [ { title: 'Coordinating Conjunctions (FANBOYS)', explanation: 'Using For, And, Nor, But, Or, Yet, So to connect two independent clauses.', examples: ['"I wanted to go, but I was too tired."'] }, { title: 'Subordinating Conjunctions', explanation: 'Using words like "although," "because," "since," and "while" to connect a dependent clause to an independent clause.', examples: ['"Although it was raining, we went for a walk."'] } ] },
  { level: 'Advanced', title: 'Punctuation Mastery', category: 'Grammar', description: 'Learn the correct use of commas, semicolons, and colons.', time: 22, subTopics: [ { title: 'The Comma Splice', explanation: 'How to identify and fix this common grammatical error where two independent clauses are joined only by a comma.', examples: ['Incorrect: "I like coffee, she likes tea."', 'Correct: "I like coffee, and she likes tea." or "I like coffee; she likes tea."'] }, { title: 'Semicolons vs. Colons', explanation: 'Understand the specific rules for using these two powerful punctuation marks.', examples: ['Semicolon: "I have a big test tomorrow; I can\'t go out tonight."', 'Colon: "I need three things: milk, bread, and eggs."'] } ] },
  { level: 'Beginner', title: 'Nouns, Verbs, and Adjectives', category: 'Grammar', description: 'Understand the basic building blocks of any English sentence.', time: 12, subTopics: [ { title: 'Identifying Nouns', explanation: 'Learn about people, places, things, and ideas.', examples: ['"The teacher (person) went to the school (place). "'] }, { title: 'Action Verbs and State Verbs', explanation: 'Understand the two main types of verbs.', examples: ['Action: "He runs every day."', 'State: "She seems happy."'] }, { title: 'Describing with Adjectives', explanation: 'Learn how to use adjectives to make your sentences more interesting.', examples: ['"It was a beautiful, sunny day."'] } ] },
  { level: 'Beginner', title: 'Pronouns', category: 'Grammar', description: 'Learn about subject, object, and possessive pronouns.', time: 14, subTopics: [ { title: 'Subject Pronouns', explanation: 'I, you, he, she, it, we, they.', examples: ['"She is a doctor."'] }, { title: 'Object Pronouns', explanation: 'me, you, him, her, it, us, them.', examples: ['"He gave the book to me."'] } ] },

  
  { level: 'Advanced', title: 'Conditionals', category: 'Advanced Grammar', description: 'Master conditional sentences to talk about hypothetical situations.', time: 25, subTopics: [ { title: 'Zero and First Conditionals', explanation: 'For real situations, facts, and likely future events.', examples: ['Zero: "If you heat water, it boils."', 'First: "If it rains, we will cancel the picnic."'] }, { title: 'Second Conditional', explanation: 'For unreal or impossible situations in the present or future.', examples: ['"If I had a lot of money, I would travel the world."'] }, { title: 'Third Conditional', explanation: 'For talking about past situations that did not happen.', examples: ['"If I had studied harder, I would have passed the exam."'] } ] },
  { level: 'Advanced', title: 'Reported Speech', category: 'Advanced Grammar', description: 'Learn how to report what other people have said.', time: 22, subTopics: [ { title: 'Reporting Statements', explanation: 'Understanding the backshift of tenses (e.g., present simple becomes past simple).', examples: ['Direct: "I am happy." -> Reported: "She said that she was happy."'] }, { title: 'Reporting Questions', explanation: 'Learn how to change question structures into statements.', examples: ['Direct: "Where do you live?" -> Reported: "He asked me where I lived."'] } ] },
  { level: 'Advanced', title: 'Relative Clauses', category: 'Advanced Grammar', description: 'Add more detail to your sentences with defining and non-defining clauses.', time: 20, subTopics: [ { title: 'Defining vs. Non-Defining Clauses', explanation: 'Learn when to use commas with relative clauses. Defining clauses are essential; non-defining clauses add extra information.', examples: ['Defining: "The man who lives next door is a doctor."', 'Non-defining: "My brother, who lives in London, is a doctor."'] }, { title: 'Using Who, Which, That, and Whose', explanation: 'Master the correct relative pronouns for people, things, and possession.', examples: ['"That is the woman who got the job."', '"This is the book that I was telling you about."'] } ] },
  { level: 'Intermediate', title: 'Modal Verbs', category: 'Advanced Grammar', description: 'Express ability, permission, advice, and obligation with modal verbs.', time: 18, subTopics: [ { title: 'Modals of Ability and Permission', explanation: 'Using "can," "could," and "may."', examples: ['"I can speak English."', '"Could I please use your phone?"'] }, { title: 'Modals of Obligation and Advice', explanation: 'Using "must," "have to," and "should."', examples: ['"You must finish your homework."', '"You should see a doctor."'] }, { title: 'Modals of Possibility', explanation: 'Using "might," "may," and "could" to talk about probability.', examples: ['"It might rain later."'] } ] },
  { level: 'Advanced', title: 'Inversion', category: 'Advanced Grammar', description: 'Learn to form more formal and emphatic sentences by inverting the subject and verb.', time: 24, subTopics: [ { title: 'Inversion with Negative Adverbials', explanation: 'Used at the beginning of a sentence for emphasis.', examples: ['"Never have I seen such a beautiful sight."', '"Not only did he arrive late, but he also forgot the documents."'] } ] },

  
  { level: 'Intermediate', title: 'Making Polite Requests', category: 'Politeness and Professional', description: 'Learn how to ask for things politely in a professional setting.', time: 15, subTopics: [ { title: 'Indirect Questions', explanation: 'Using phrases like "Could you tell me..." and "I was wondering if..." to sound more polite.', examples: ['Direct: "Where is the bathroom?" -> Indirect: "Could you tell me where the bathroom is?"'] }, { title: 'Softening Your Language', explanation: 'Using words like "just," "a little," or "possibly" to sound less direct.', examples: ['"I was just wondering if you had a moment to chat."'] } ] },
  { level: 'Intermediate', title: 'Giving and Receiving Feedback', category: 'Politeness and Professional', description: 'Learn professional language for giving constructive criticism and responding to it.', time: 20, subTopics: [ { title: 'The Sandwich Method', explanation: 'A popular technique for giving feedback constructively by starting with a positive, giving the criticism, and ending with a positive.', examples: ['"You did a great job on the presentation design. The data section could be a bit clearer. Overall, it was a strong effort."'] }, { title: 'Accepting Criticism Gracefully', explanation: 'Phrases to use when you receive feedback on your work.', examples: ['"Thank you for the feedback, that is very helpful."', '"I understand. I will work on that for next time."'] } ] },
  { level: 'Beginner', title: 'Professional Email Etiquette', category: 'Politeness and Professional', description: 'Learn the dos and don\'ts of writing professional emails.', time: 25, subTopics: [ { title: 'Proper Greetings and Closings', explanation: 'How to start and end your emails professionally.', examples: ['Greeting: "Dear Mr. Smith,"', 'Closing: "Sincerely," or "Best regards,"'] }, { title: 'Subject Line Best Practices', explanation: 'Write clear and concise subject lines that get your emails opened.', examples: ['Good: "Meeting Request: Q3 Project Review"', 'Bad: "hello"'] } ] },
  { level: 'Advanced', title: 'Participating in Meetings', category: 'Politeness and Professional', description: 'Learn key phrases for interrupting politely, expressing opinions, and agreeing or disagreeing.', time: 22, subTopics: [ { title: 'Interrupting Politely', explanation: 'Phrases like "Sorry to interrupt, but..." and "May I add something quickly?"', examples: ['"Sorry to interrupt, but could I ask a quick question about the budget?"'] }, { title: 'Expressing Agreement and Disagreement', explanation: 'Learn how to agree and disagree in a professional and respectful way.', examples: ['Agreeing: "I completely agree." / "That\'s a great point."', 'Disagreeing: "I see your point, but I have a different perspective."'] } ] },
  { level: 'Beginner', title: 'Small Talk for Networking', category: 'Politeness and Professional', description: 'Master the art of small talk to build connections in professional environments.', time: 18, subTopics: [ { title: 'Safe Topics for Conversation', explanation: 'Learn what topics are appropriate for professional small talk, such as work, travel, and hobbies.', examples: ['"Have you worked here long?"', '"Are you attending the conference tomorrow?"'] }, { title: 'Asking Open-Ended Questions', explanation: 'Keep the conversation going by asking questions that require more than a "yes" or "no" answer.', examples: ['Good: "What did you think of the presentation?"', 'Bad: "Did you like the presentation?"'] } ] },
  { level: 'Advanced', title: 'Advanced Negotiation Phrases', category: 'Politeness and Professional', description: 'Learn sophisticated language for negotiation and persuasion.', time: 28, subTopics: [ { title: 'Presenting a Proposal', explanation: 'Language for clearly and confidently presenting your terms.', examples: ['"We propose a deadline of June 30th."', '"Our initial offer is..."'] }, { title: 'Handling Objections', explanation: 'Phrases for professionally addressing concerns and disagreements.', examples: ['"I understand your concern about the timeline. Let\'s discuss how we can address that."'] } ] },

  
  { level: 'Intermediate', title: 'Storytelling Techniques', category: 'Usage In Context', description: 'Learn how to structure a story in English to engage your audience.', time: 25, subTopics: [ { title: 'Using Transition Words', explanation: 'Connect your ideas smoothly with words like "first," "next," "then," and "finally."', examples: ['"First, I woke up. Then, I had breakfast."'] }, { title: 'Past Tense for Storytelling', explanation: 'Practice using the simple past and past continuous to tell a story.', examples: ['"The sun was shining and the birds were singing. Suddenly, a car drove by."'] } ] },
  { level: 'Intermediate', title: 'Expressing Opinions and Beliefs', category: 'Usage In Context', description: 'Learn various phrases to share your point of view clearly and politely.', time: 16, subTopics: [ { title: 'Formal Opinion Phrases', explanation: '"In my opinion...", "I believe that...", "From my perspective..."', examples: ['"In my opinion, the project needs more funding."'] }, { title: 'Informal Opinion Phrases', explanation: '"I think...", "I feel like...", "If you ask me..."', examples: ['"I think we should leave now."'] } ] },
  { level: 'Beginner', title: 'Making Suggestions and Recommendations', category: 'Usage In Context', description: 'Learn how to propose ideas and give advice to others.', time: 14, subTopics: [ { title: 'Using "Should" and "Ought to"', explanation: 'The most common ways to give advice.', examples: ['"You should get more sleep."', '"We ought to finish this today."'] }, { title: 'Using "How about...?" and "What about...?"', explanation: 'Polite ways to make a suggestion in a group.', examples: ['"How about we order pizza for dinner?"'] } ] },
  { level: 'Advanced', title: 'Describing Data and Trends', category: 'Usage In Context', description: 'Learn the specific vocabulary needed to describe charts and graphs.', time: 28, subTopics: [ { title: 'Verbs for Increase and Decrease', explanation: 'Learn words like "soar," "plummet," "fluctuate," and "stabilize."', examples: ['"Sales increased sharply in the third quarter."'] }, { title: 'Adverbs of Degree', explanation: 'Use adverbs like "sharply," "gradually," and "slightly" to add detail.', examples: ['"The temperature dropped slightly overnight."'] } ] },
  { level: 'Beginner', title: 'Asking for Clarification', category: 'Usage In Context', description: 'Never be confused again. Learn phrases to ask for help when you don\'t understand.', time: 12, subTopics: [ { title: 'Polite Interruption', explanation: 'How to politely stop someone to ask a question.', examples: ['"Excuse me, could I ask a question?"'] }, { title: 'Key Phrases', explanation: '"Could you repeat that?", "What does that mean?", "Could you explain in another way?"', examples: ['"I\'m sorry, I didn\'t understand the last part. Could you explain it again?"'] } ] },
  { level: 'Intermediate', title: 'Comparing and Contrasting', category: 'Usage In Context', description: 'Learn the language needed to discuss similarities and differences.', time: 18, subTopics: [ { title: 'Words for Comparison', explanation: 'Using words like "similarly," "likewise," and "also."', examples: ['"Running is good exercise. Likewise, swimming is also very beneficial."'] }, { title: 'Words for Contrasting', explanation: 'Using words like "however," "on the other hand," and "in contrast."', examples: ['"I love hot weather; however, my brother prefers the cold."'] } ] },
  
  
  { level: 'Intermediate', title: 'Paragraph Structure', category: 'Writing Skills', description: 'Learn how to write well-structured paragraphs with a topic sentence and supporting details.', time: 20, subTopics: [ { title: 'The Topic Sentence', explanation: 'Understand that the topic sentence is the main idea of the paragraph.', examples: ['"There are several reasons why learning English is important for career growth." (This would be the topic sentence of a paragraph)'] }, { title: 'Supporting Sentences', explanation: 'Learn to provide details, examples, and evidence to support your topic sentence.' } ] },
  { level: 'Beginner', title: 'Capitalization Rules', category: 'Writing Skills', description: 'Master the basic rules of capitalization in English writing.', time: 10, subTopics: [ { title: 'Start of a Sentence', explanation: 'Always capitalize the first word of a sentence.' }, { title: 'Proper Nouns', explanation: 'Capitalize specific names of people, places, and organizations.', examples: ['"My name is John and I live in Addis Ababa."', '"I work for Google."'] } ] },
  { level: 'Advanced', title: 'Essay Writing Basics', category: 'Writing Skills', description: 'Learn the fundamental structure of a five-paragraph essay.', time: 30, subTopics: [ { title: 'The Introduction and Thesis Statement', explanation: 'How to grab the reader\'s attention and state your main argument.' }, { title: 'Body Paragraphs', explanation: 'How to structure each body paragraph with a topic sentence, evidence, and analysis.' }, { title: 'The Conclusion', explanation: 'How to summarize your arguments and provide a final thought.' } ] },
];
  
export const learnPageTips = [ 'Identify the parts of speech in simple sentences.', 'Practice using articles with nouns daily.', 'Expand short sentences using prepositions.', 'Combine sentences using conjunctions and connectors.', ];